#!/usr/bin/perl
# Builds page 2 (price sheet) of tools/submission-form.html from tools/price-list.json.
# Re-runnable: replaces whatever sits between the PRICE-SHEET markers.
#   perl tools/build-price-sheet.pl
use strict; use warnings;
use JSON::PP;

my $root = $0; $root =~ s{[\\/]tools[\\/][^\\/]+$}{}; $root = '.' if $root eq $0;
my $json_file = "$root/tools/price-list.json";
my $form_file = "$root/tools/submission-form.html";

sub slurp { local $/; open my $f, '<:raw', $_[0] or die "$_[0]: $!"; <$f> }
my $items = JSON::PP->new->utf8(0)->decode(slurp($json_file));

# Tiers presented as grouped lists; every other price gets its own table row
my @TIERS = (215, 290, 450);
my %is_tier = map { $_ => 1 } @TIERS;

# Same receipt wording as the "How to submit" note on page 1
use constant PAYMENT_NOTE => 'Submission forms are accepted by email only, using the Email the Lab button on our website. Once your emailed form is received, a confirmation of receipt and a payment link for the tests ordered will be sent to the address given in Email for Results.';

sub clean {
  my $n = shift;
  $n =~ s/\s+analysis$//;                 # section headings already say "analysis"
  $n =~ s/\(\s+/(/g; $n =~ s/\s+\)/)/g;   # "( MOD GRF (1-29) )" -> "(MOD GRF (1-29))"
  $n =~ s{/\s+}{/}g;                      # "GHK-Cu/ TB-500" -> "GHK-Cu/TB-500"
  $n =~ s/^Glutathion$/Glutathione/;      # spelling
  $n =~ s/^N-acetyl/N-Acetyl/;               # source mixes the two casings
  return $n;
}
sub esc { my $s = shift; $s =~ s/&/&amp;/g; $s =~ s/</&lt;/g; $s =~ s/>/&gt;/g; $s }
sub by_name { lc(clean($a->{name})) cmp lc(clean($b->{name})) }

my (%tier, @special);
for my $it (@$items) {
  if ($is_tier{$it->{price}}) { push @{ $tier{$it->{price}} }, $it } else { push @special, $it }
}

my $html = '';
$html .= qq~<!-- PRICE-SHEET:START (generated by tools/build-price-sheet.pl — edit price-list.json, not this block) -->\n~;
$html .= qq~<div class="price-page">\n<header>\n  <h1>PRICE SHEET</h1>\n  <div class="lab">VeriPure Labs</div>\n~;
$html .= qq~  <div class="contact">Independent Third-Party Analytical Testing | Email: RESULTS\@VERIPURELABS.COM | Web: WWW.VERIPURELABS.COM</div>\n</header>\n~;
$html .= qq~<div class="instr">\n  <span>All prices in USD, per analysis. Each sample row on the submission form is one analysis.</span>\n  <span>Peptide Analysis</span>\n</div>\n\n~;

$html .= qq~<section>\n  <h2>Single-Peptide Analysis</h2>\n~;
for my $p (@TIERS) {
  my @list = sort by_name @{ $tier{$p} || [] };
  my $n = scalar @list;
  $html .= qq~  <div class="tier">\n    <div class="tier-price"><b>\$$p</b><span>$n compounds</span></div>\n    <ul class="tier-list">\n~;
  $html .= join '', map { "      <li>" . esc(clean($_->{name})) . "</li>\n" } @list;
  $html .= qq~    </ul>\n  </div>\n~;
}
$html .= qq~</section>\n\n~;

$html .= qq~<section>\n  <h2>Blends, Multi-Analyte &amp; Specialty Analysis</h2>\n  <table class="price-table">\n~;
$html .= qq~    <thead><tr><th>Analysis</th><th style="width:70pt;text-align:right">Price (USD)</th></tr></thead>\n    <tbody>\n~;
for my $it (sort { $a->{price} <=> $b->{price} or by_name() } @special) {
  $html .= "      <tr><td>" . esc(clean($it->{name})) . "</td><td class=\"amt\">\$$it->{price}</td></tr>\n";
}
$html .= qq~    </tbody>\n  </table>\n</section>\n\n~;

$html .= qq~<section>\n  <h2>Optional Tests</h2>\n  <p class="price-note">Optional tests A–D on the submission form (Peptide Content, Water Content, Residual Solvents, Bacterial Endotoxins) are quoted on request. Contact RESULTS\@VERIPURELABS.COM with the samples and tests required.</p>\n</section>\n\n~;
$html .= qq~<section>\n  <h2>Payment</h2>\n  <p class="price-note">~ . PAYMENT_NOTE . qq~</p>\n</section>\n\n~;
$html .= qq~<footer>\n  VeriPure Labs is aligned with ISO 9001 and Good Laboratory Practice (GLP) principles. All testing and reports issued are strictly for research use only.<br>\n  <span style="font-weight:400">Prices subject to change without notice · Price Sheet VPL-PS · Rev. 09/2026</span>\n</footer>\n</div>\n<!-- PRICE-SHEET:END -->\n~;

# ---- Integrity check: every source item appears exactly once, at its source price
my $emitted_rows = () = $html =~ /<li>|<tr><td>/g;
die "expected ".scalar(@$items)." items, emitted $emitted_rows\n" unless $emitted_rows == @$items;
my $src_sum = 0; $src_sum += $_->{price} for @$items;
my $out_sum = 0;
while ($html =~ /<div class="tier-price"><b>\$(\d+)<\/b><span>(\d+) compounds/g) { $out_sum += $1 * $2 }
while ($html =~ /class="amt">\$(\d+)</g) { $out_sum += $1 }
die "price total mismatch: source $src_sum, sheet $out_sum\n" unless $src_sum == $out_sum;

my $css = <<'CSS';
  /* PRICE-SHEET-CSS:START */
  .price-page { break-before: page; }
  .tier { display: grid; grid-template-columns: 62pt 1fr; border: .75pt solid var(--rule); margin-bottom: 5pt; }
  .tier-price { background: var(--bar); border-right: 3pt solid var(--blue); display: flex; flex-direction: column;
                justify-content: center; align-items: center; padding: 5pt 4pt; }
  .tier-price b { font-size: 17pt; font-style: italic; color: var(--navy); line-height: 1; }
  .tier-price span { font-size: 6.8pt; font-style: italic; color: var(--muted); margin-top: 2pt; }
  .tier-list { list-style: none; margin: 0; padding: 5pt 8pt; columns: 4; column-gap: 10pt; font-size: 8pt; }
  .tier-list li { margin: 0 0 1.6pt; break-inside: avoid; padding-left: 7pt; position: relative; }
  .tier-list li::before { content: ""; position: absolute; left: 0; top: 3.6pt; width: 3pt; height: 3pt; background: var(--blue); border-radius: 50%; }
  .price-table td { height: 14pt; font-size: 8.2pt; }
  .price-table td.amt { text-align: right; font-weight: 700; font-style: italic; color: var(--navy); }
  .price-table tbody tr:nth-child(even) td { background: var(--field); }
  .price-note { margin: 0; font-size: 8pt; font-style: italic; }
  /* PRICE-SHEET-CSS:END */
CSS

my $form = slurp($form_file);
$form =~ s{\n?<!-- PRICE-SHEET:START.*?<!-- PRICE-SHEET:END -->\n}{}s;
$form =~ s{\n?  /\* PRICE-SHEET-CSS:START \*/.*?/\* PRICE-SHEET-CSS:END \*/\n}{}s;
$form =~ s{</style>}{$css</style>} or die "no </style>\n";
$form =~ s{</body>}{$html\n</body>} or die "no </body>\n";

open my $o, '>:raw', $form_file or die; print $o $form; close $o;
printf "ok  %d items (%d tiered, %d specialty), price total %d\n", scalar(@$items), scalar(@$items) - @special, scalar(@special), $src_sum;
